version: 2
versionName: "1.0.3"

packageName: remoteHelp
appName: "Запросить помощь"
appUUID: "919b31d4-84e2-436f-a780-57b61e2e1acf"
iconColor: "#546E7A"

capabilities:
  - navigation
  - storage
  - http
  
views:
  - name: launcher
    header: "Запросить помощь"
    source: client/views/help-screen/help-screen.html
    scripts: # список скриптов которые должны быть подключены
      - help-screen.js
    styles: # список стилей которые должны быть подключены
      - "*.css" # может подключить все файлы

daemons:
  - name: suggestion
    events:
    - null
    behavior: suggestion-daemon.js

plugins:
  - name: suggestion
    moments:
    - null
    point: before
    behavior: before-receipt-fixed.js